---
# This workflow will install Python dependencies and run tests
# across operating systems, select versions of Python, and user + dev environments
# For more info see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python 🐍 CI/CD tests

on:
  push:
    branches: [main, develop]
    paths-ignore: # prevents workflow execution when only these types of files are modified
      - "**.md" # wildcards prevent file in any repo dir from trigering workflow
      - "**.bib"
      - "**.ya?ml" # captures both .yml and .yaml
      - "LICENSE"
      - ".gitignore"
  pull_request:
    branches: [main, develop]
    paths-ignore:
      - "**.md"
      - "**.bib"
      - "**.ya?ml"
      - "LICENSE"
      - ".gitignore"
  workflow_dispatch: # also allow manual trigger, for testing purposes

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        py-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python ${{ matrix.py-version }}
        run: uv python install ${{ matrix.py-version }}

      - name: Install package and test deps
        run: uv sync --extra testing

      # 🔧 Install GLPK solver
      - name: Install GLPK
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update && sudo apt-get install -y glpk-utils
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install glpk
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            choco install glpk --no-progress
          fi
        shell: bash

      - name: Test with pytest
        run: uv run pytest

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
